spring:
  datasource:
    url: jdbc:mysql://${mc.host.mysqlserver}:3306/mc_device_cloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mc:
  host:
    admin-server: 192.168.2.186
    kafkaserver: 192.168.2.186:9092
    influxdbserver: 192.168.2.196
    eurekaserver: 192.168.2.186
    mysqlserver: 192.168.2.186